### ISSUE TITLE
why :it's too low sir?

### ISSUE THREAD

**Issue by 564064202** [Hutchison-Technologies/nat-type-identifier#5]
but when we use other js(https://raw.githubusercontent.com/nthack/NatTypeChecker/main/checker.js),
it's fast

**Comment by jwh-hutchison** [comment]
It's based on the process flow of https://pypi.org/project/pystun/ so any inefficiencies in the processing come from that. I didn't design the code, I just implemented the JS equivilant.

**Comment by 564064202** [comment]
> It's based on the process flow of https://pypi.org/project/pystun/ so any inefficiencies in the processing come from that. I didn't design the code, I just implemented the JS equivilant.

when the nat is Symmetric,it will waste 1min

**Comment by jwh-hutchison** [comment]
It's based on the process flow of https://pypi.org/project/pystun/ - this implementation of the library may have been rushed and inefficiencies may exist because of that but I'm afraid I don't have enough time to improve the code at the moment, but if anyone wants to then please feel free to open a pull request and I'll review it.
